name: attempt3
description: Attempt 3 app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# --- SECCIÓN DE DEPENDENCIAS ---
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  path_provider: ^2.1.4
  dio: ^5.4.3
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  package_info_plus: 9.0.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- SECCIÓN DE FLUTTER ---
flutter:
  uses-material-design: true

  assets:
    - assets/audio/