name: attempt3
description: Attempt 3 app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
dependencies:
  # ... otros paquetes
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
    shared_preferences: ^2.2.3 
    uses-material-design: true
    assets:
    - assets/audio/ # <-- Añade esta línea

  # --- librerías que usa updater.dart ---
  http: ^1.2.2
  package_info_plus: ^8.0.0
  dio: ^5.6.0
  path_provider: ^2.1.4
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
