name: Deploy Website to Firebase Hosting

# Este es el disparador: se ejecuta cuando un release es publicado.
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio para tener acceso a tus archivos (como index.html)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Reemplaza el enlace en index.html con el del nuevo release
      - name: Update download link in index.html
        run: |
          # Esta línea usa una herramienta (sed) para buscar y reemplazar el href del botón.
          # Toma la URL del primer archivo adjunto (.apk) del release que activó el workflow.
          sed -i 's|href="https://github.com/[^"]*"|href="${{ github.event.release.assets[0].browser_download_url }}"|' public/index.html
      
      # 3. Instala Node.js, necesario para instalar las herramientas de Firebase
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. Instala las herramientas de Firebase
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Despliega a Firebase Hosting
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive